[template]
src = "db-connection-pools.xml.tmpl"
dest = "/home/gfish/dbc-payara.d/51-db-connection-pools.xml"

keys = [
  "/dbc/postgres/filestore/env/postgres/password",
  "/dbc/postgres/filestore/env/postgres/user",
  "/dbc/postgres/filestore/env/postgres/db",
  "/dbc/postgres/filestore/env/postgres/port",
  "/dbc/postgres/filestore/env/postgres/servername"
]
