[template]
src = "db-connection-pools.xml.tmpl"
dest = "/home/gfish/dbc-payara.d/19-db-connection-pools.xml"

keys = [
  "/dbc/postgres/jobstore/env/postgres/host",
  "/dbc/postgres/jobstore/env/postgres/password",
  "/dbc/postgres/jobstore/env/postgres/user",
  "/dbc/postgres/jobstore/env/postgres/port",
  "/dbc/postgres/jobstore/env/postgres/db"
]


